### ISSUE TITLE
Art-net Control?

### ISSUE THREAD

**Issue by BB21B** [taburineagle/NeewerLite-Python#11]
Control via Art-net would be really nice. I'm going to start playing with this and maybe work on it but I thought I'd put the idea out there.

**Comment by taburineagle** [comment]
That's interesting, I've never actually heard of that protocol, but that _would_ be nice.  Ha, this one might be a bit out of my league at the moment though 😅  I'm wondering how that would work - I'm guessing there'd be an interpreter converting Art-net commands into Bluetooth commands the Neewer lights can use.

**Comment by taburineagle** [comment]
Got you, got you - the thing I'm curious about with it though is how to interface that protocol to the Neewer lights, since they just use Bluetooth.  I would assume it's just a manner of listening for a specific command from the board to the NeewerLite-Python program, then a conversion from whatever value that command is doing, to a converted command that a Neewer light can use.

**Comment by BB21B** [comment]
Exactly, artnet broadcasts over the network.  Then this could be running on say a RaspberryPI. You've already done the hard bit of actually working on the protocol.

I will have a play when I have some time and see if I can implement.

Each DMX addresses is just and 8 bit integer. A single fixture will just multiple addresses Though it's common to combine two addresses for 16 bit control. I would probably just expose this as follows.

So like
1 - INTENSITY
2/3 - HUE
4/5 - SAT
6/7 - COLOUR TEMP
6 - effects channel

**Comment by taburineagle** [comment]
Got you - interesting!  I'm curious to see what you'll implement - as far as I know, I have no way of testing that protocol out on my end, but I may be wrong, I literally didn't even know it existed until last night, and I've been in broadcast TV for 20+ years 🤣

**Comment by BB21B** [comment]
It's very useful when you have like 30 universes odd for pixel mapping without having to distribute loads of individual DMX lines that is for sure.

Check out the Open Lighting Project too for some interest.

Plenty of free options to test artnet though. Even ETC EOS can be ran in offline mode for free and that'll spit out artnet happily with random interruptions in the data.

Anyway I just got the panels out of the shed and a spare Pi4 so yeah I have some plans. I have the 660 RGB ones.

I've always been based in theatre/events until covid, so it's pretty much bread and butter for me. Now moved onto corporate studio stuff and building all kinds of fun things.

**Comment by taburineagle** [comment]
Ah, very nice!  I'll check that out, and I look forward to seeing what you develop!

**Comment by BB21B** [comment]
Hey again, been going through the code and now have some basic artnet functionality.

Really just a test, at the moment updating individual lights with unique values seems a little awkward with the thread and the sendValue var. I think I'll need to add my own functionality there rather than trying to squeeze it in to the existing function that writes the values. 
Right now it's just sending values from artnet to whatever is selected in the GUI

Also I had terrible performance on a Raspberry Pi 4, I think it might be down to the Bluetooth chipset. Regularly disconnects or fails to send. Multiple lights only worked one time and not for very long.
I will try a USB adapter, it'll will probably work better.

Pretty much flawless on my Mac though (though I'm not sure the lights like to receive data at 30Hz for very long if the values are changing constantly, occasionally fails to send)

Would like to see some auto-reconnect on a send failure too, doesn't always seem to attempt it in all circumstances.

Anyway that was only one evening of playing around and reading your code, when I have a bit more done I'll post my progress

**Comment by taburineagle** [comment]
Very nice, sounds promising - are you using the GUI for the connections to Artnet then, or a different method like HTTP?

**Comment by taburineagle** [comment]
Hi @BB21B - I'm going to close this as it's been a while and I haven't heard anything lately... if you have anything else to add to the issue, please feel free to reopen it!
