### ISSUE TITLE
Question: Is it possible to leave the connection open instead of closing it each time?

### ISSUE THREAD

**Issue by chubmeister** [taburineagle/NeewerLite-Python#13]
I'm trying to figure out if it's possible to leave a light connected to my pc so it doesn't need to reconnect every time I want to change light settings. The delay between the command being sent and actually running is pretty long, I'm hoping a constant connection would solve the issue.

**Comment by taburineagle** [comment]
Hello @chubmeister!  Which mode are you using to send commands?  GUI, CCT or HTTP mode?  Both the GUI and HTTP modes allow consistently open connections, but the CLI (command-line interface) doesn't.

**Comment by chubmeister** [comment]
Hey, I'm using the CCT mode.
Can I send the commands through HTTP using batch scripts?

**Comment by taburineagle** [comment]
You should be good if you're using a program like curl in your batch script, where you can send it URLs.

**Comment by chubmeister** [comment]
If I remember correctly it was just freezing up when using curl. I'll look
into it again.

**Comment by taburineagle** [comment]
If I send curl a command to the NeewerLite-Python server from another computer on my network to control the lights, it doesn't seem to hang on my end - make sure you have the port number in the URL as well -

`curl "http://10.0.0.12:8080/NeewerLite-Python/doAction?light=1;2&mode=CCT&temp=52&bri=50"`

**Comment by taburineagle** [comment]
Make sure you have the latest versions of NeewerLite-Python too - there _was_ an issue (#10) a few versions back where if you used Chrome, it would monopolize the server and other requests would fail, but that's been fixed since then.

**Comment by chubmeister** [comment]
Got it working, thanks. Adding in the quotes worked, didn't like the
arguments otherwise.
Instantaneous now. Works awesome.

**Comment by taburineagle** [comment]
Ah, awesome!  Yeah, depending on which interface you're running curl from, & and ; will trip the command up if you don't enclose it in quotation marks.
