### ISSUE TITLE
RGB480 provoked an error

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#21]
I just added my 480RGB light to the setup.
It is an RGB light like the 660 with multiple channels and colours.

It connected, and I could set the brightness and white tone, and then I saw this:

```
[18:32:03] - Background Thread Running
Exception in thread workerThread:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "d:\neewer\NeewerLite-Python.py", line 1553, in workerThread
    _loop.run_until_complete(getLightChannelandPower(a))
  File "D:\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\neewer\NeewerLite-Python.py", line 1356, in getLightChannelandPower
    powerInfo = await readNotifyCharacteristic(selectedLight, [120, 133, 0, 253], 2)
  File "d:\neewer\NeewerLite-Python.py", line 1341, in readNotifyCharacteristic
    if receivedData != "" and receivedData[1] == typeOfData: # if we've received data, and the data returned is the right *kind* of data, then return it
IndexError: bytearray index out of range
```

And now it doesn't react on commands from Neewerlite

**Comment by taburineagle** [comment]
Ah, I know why this is - because again, the data it was receiving from that light was something along the lines of `b'6`, which has only one element, but it's looking for the 2nd element.  This one is easy to fix, I will post a commit later on tonight.

**Comment by taburineagle** [comment]
OK, the new release (0.8) _should_ fix this issue - I implemented a check in the power/channel return logic that returns a default "---" value if the light doesn't provide the routine with enough data (this _should_ eliminate the `IndexError: bytearray index out of range` issue.

**Comment by fribse** [comment]
It looks quite a bit better, I will monitor it, I've just reinstalled the PC, so it's a bit chaotic with missing this and that at the moment :-)

**Comment by taburineagle** [comment]
Ha, yeah, I had to do that at one point last year too - that's always fun trying to figure out what you're missing 2 weeks later!

**Comment by fribse** [comment]
Yup, like all my davinci resolve projects 😢  Ahh well.
Back to the issue, I don't see the error currently, and I haven't seen it since the last push, so I'll close this I guess?

**Comment by taburineagle** [comment]
Excellent, sounds good - ha, _yes_!  DaVinci Resolve!  I have been a professional editor for decades, and used a _lot_ of different linear systems and NLEs, and I still prefer coming back to Resolve - and it's (technically) free, if you're using the standard version 😊

**Comment by fribse** [comment]
😁  then I hope you don't find my YT channel, you would be horrified of the bad job I do 😆

**Comment by taburineagle** [comment]
Hehe, nah!  Not unless you use constant star wipes for every shot! 🤣
