### ISSUE TITLE
Enhancement Down the Line: Light mode/settings presets

### ISSUE THREAD

**Issue by taburineagle** [taburineagle/NeewerLite-Python#23]
- [X] Write preset logic (possibly embed this information in the `light_prefs` files)
- [X] Write GUI elements to launch these presets
- [X] Push the commit live

**Comment by taburineagle** [comment]
@frisbe - This is the starting block of the custom presets section - not much to look at for the moment, but the pre-defined settings have been added.

**Comment by taburineagle** [comment]
@fribse - This is the starting block of the custom presets section - not much to look at for the moment, just a list of parameters for the "default", non-custom preset settings, but it's the start...

**Comment by taburineagle** [comment]
It's coming along nicely @fribse! - I'm still kicking the tires on all of it thoroughly before setting it into the wild, but it's coming along nicely!  There are 8 custom presets available - in the beginning, they're set up as 8 default presets, but there are also going to be 2 different kinds of custom presets you can sat any of those 8 slots to - "global" presets control one set of parameters for all lights selected (so, all white, all red, all 5600K @ 50%, etc,), and "snapshot" presets store the parameters of every single light at that point in time (or for specific lights, if you choose to only use a few instead of all of them), so you could, for example, have 2 lights set as a backdrop with 2 different HSI color settings, one side light in CCT mode for spotlight, and a fill light on the side, and one snapshot preset would set all of those parameters up at the same time.  I've also coded a "preview" for the snapshot presets, that when you hover over an icon for a snapshot preview, the table will highlight the affected lights in green to show which ones will change for that specific snapshot preset.

![image](https://user-images.githubusercontent.com/18430526/151064660-6ae47092-cfed-4d9e-89b9-488acc31dde4.png)

**Comment by fribse** [comment]
Looks very promising!

**Comment by taburineagle** [comment]
Thanks!  **IT'S LIVE!!**  I just pushed the commit and made a new release - I'll do more properly showing all it can do in the future (a lot of family things going on at the moment, so I'm not 100% sure when I'll be able to do that!) - but I want to do a video showcasing all kinds of different preset configurations.

**Comment by fribse** [comment]
Darned, that IS really nice, didn't really figure out the way to set the presets until I f.... up my settings, but after that, it worked very nicely, and the light preferences with custom names, weehee, it's much easier to see which light is which then.
One thing, and I guess that is by design, they don't store the 'on/off' state in the 'custom snap'?

**Comment by taburineagle** [comment]
Thanks!  Ha, sorry about the settings - I want to more properly document the preset options, how to set and clear them, etc., in either the wiki, or a video, or both, but they're definitely versatile with what you can do with them!  The latest commit (pushed yesterday) also adds a small tool tip on the lights that are affected, showing what their preset does to them (mode, hue, etc.) -

![image](https://user-images.githubusercontent.com/18430526/151677790-d1105a29-b456-49ca-be5a-d158ebba9db3.png)

They don't store the power setting _yet_, although that wouldn't be too hard to code in.  I've been basically treating 0% as "power off" for that, because of the issue with the battery-only-powered Neewer lights (like the RGB176) shutting down entirely after a few minutes of being in standby mode.

**Comment by taburineagle** [comment]
Right, right, got ya @fribse - I'm working on that now :)  Haven't had a lot of time the last few days to work on it, but I wanted to do a "if the light is off, then store that" section, as well as turning lights on that have a value set that are currently off.

**Comment by taburineagle** [comment]
@fribse - I added that in!  Note, for this to work (by design), the light has to actually be told to "be off" (it has to be turned off via the "Turn Light(s) Off" button) - when you store a snapshot preset, that value will be stored with it, so if you have one light off and 2 lights on in the preset, that light should turn off when clicking on that preset (if it's currently on), and turn on when clicking another stored snapshot preset with it not off.

**Comment by fribse** [comment]
Hey, that sounds very clever, I'll do an update later today :-)

**Comment by taburineagle** [comment]
Nice!  I updated all of the documentation for custom presets on the Wiki too - 

https://github.com/taburineagle/NeewerLite-Python/wiki/(1)-The-GUI-(Graphical-User-Interface)
