### ISSUE TITLE
RGB480 will not connect any longer?

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#28]
Hey there

NeewerLite-Python 0.9

For some reason my RGB480 won't connect ano more.
I can sometimes see an empty line in the GUI.
I can connect to it without any issues from the App.
I've tried setting the light to different channels, so far without success.

**Comment by taburineagle** [comment]
Hmm, very odd - is it just the RGB480 that's having issues?

**Comment by fribse** [comment]
Yes, well, today it connects again, that is really odd...

**Comment by taburineagle** [comment]
It's possible that you had the app still active on the phone in some form and the 480 was still connected to it, so NeewerLite-Python couldn't connect to it.  I've had that happen before.

**Comment by taburineagle** [comment]
That is very odd!  I'm honestly just as confused :/  It is just happening to the RGB480, correct?  Ha, the phone _might_ be faster, but at the end of the day it comes down to how the dongle and Bleak handle things 😅  NeewerLite-Python is just an intermediary to Bleak.  Reinstalling NeewerLite-Python _shouldn't_ make a difference either way (I think that's what you mean by "installing the app" - I'm not sure though), as the actual infrastructure is still the same (it's possible turning the BT radio off and on again refreshed the connection), the only thing that I'm wondering is if the light is just barely at the edge of getting a signal to the Bluetooth of the computer, so sometimes it's _just_ connecting and sometimes it's _just_ out of range.  It's down to the capabilities of BT dongles and Bleak (for example, my Macbook with built-in Bluetooth can connect to a light on the other side of the room in most cases, and sometimes my PC's BT dongle can't see a light 3 feet away), and phone BT radios are usually a bit more powerful - no 2 setups are the same, especially if there's any source of interference in them.

**Comment by taburineagle** [comment]
Ha, to add to that, sometimes my Raspberry Pi setups with internal Bluetooth are even weaker than the PC's BT receiver, so they have even less success with connections (although those Pis are Pi Zeros in those setups, so their BT radios may be slightly weaker, _and_ they are trying to receive from inside of a plastic enclosure, so that may be attenuating the signal).

**Comment by taburineagle** [comment]
Got you, interesting about the Pi Z Wifi/BT issue, I wasn't aware of that - ha, but now that you mention it, I have had issues with the Pi Z testing both the Wifi (for sending info back to my main Camera diagnostics system) and BT simultaneously (when trying to interface with the lights), so good to know.  Yeah, I know it's frustrating when one thing works and another similar thing doesn't (ha, especially as a developer of _one_ of those 2 things 😅), but I'm not sure on this one other than either an issue with the dongle's strength (which is highly possible), or Bleak (which might be possible too, but it sounds more like an intermittent connection issue to me).  The light having a less strong transmitter is possible too, but it's hard to say.

**Comment by taburineagle** [comment]
I just noticed, in this picture you shared in the "Attempt 7 of 6" post, the RSSI (signal level) for the 480 was _really_ low (well, _high_, but high is low) - a lower number like in the range of the mid -60s to -40 is decent, -70s are doable, but -88 is a _really_ weak signal - 

![image](https://user-images.githubusercontent.com/18430526/156397425-f04c175d-26a5-4d47-a8f9-215ebf2a142c.png)

This one of the RGB176 has a much better RSSI (this is from the "New light tested" thread - 

![image](https://user-images.githubusercontent.com/18430526/156398210-fc15a412-800c-4410-9b4d-b2b41ee12e37.png)

**Comment by fribse** [comment]
The Antenna in the RGB480 SUCKS 😆 
I've put the dongle on an extender cord, and placed it rather close, it's placed above the monitor, only 40 cm from the light.
The three other lights are 100-120 cm away from the dongle, this is what it shows:

![billede](https://user-images.githubusercontent.com/13660621/156558142-e9fddd6f-2b13-44f7-8c9f-4a6a5d4c63c5.png)

I think it must be the antenna quality, so I look forward to receiving the 'big antenna' BT dongle.

**Comment by taburineagle** [comment]
Ha, that sucks!  Hopefully the big antenna helps out with the reception! 😊
