### ISSUE TITLE
Unable to control brightness/temp on SNL530

### ISSUE THREAD

**Issue by PrezP** [taburineagle/NeewerLite-Python#36]
I have a SNL530 that I have successfully connected via HTTP on Raspberry Pi. The on/off command works, but brightness and temp do not. This is using CCT mode. 
There are no functionality issues when connecting the light with the official Neewer phone app. I'm guessing the protocol for these lights is slightly different?

**Comment by taburineagle** [comment]
Hi @PrezP!  One question, and one "try this" - is the SNL530 a bi-color (only CCT mode is available) light, or RGB (full-spectrum color) light?  If it's a bi-color light, then they do use a different protocol - **but** - try this first - make sure you have the light selected, click on the "Light Preferences" tab, then "This light can only use CCT mode", and then "Save Preferences" - you _should_ be able to control those commands with that setting turned on.

![Setting](https://user-images.githubusercontent.com/18430526/160281093-900fa78b-0e9a-4da3-92c6-d879418f662b.jpg)

**Comment by taburineagle** [comment]
Ahh, I just noticed the Raspberry Pi comment too - if you don't have access to the GUI, you can create the preferences file for that light like this:

- If there isn't one yet, create a `light_prefs` folder in the same folder as NeewerLite-Python
- Create a text file in that new folder with a name that's the same as the MAC address of the light, but with no ":"s
   (for example, if the light's MAC address is `11:22:33:44:55:66` then make a file called `112233445566`)
- In that new text file, add this line, and save it:
   `|False|True`
- And then re-launch NeewerLite-Python

**Comment by PrezP** [comment]
Thanks @taburineagle, I followed your instructions and this works! SNL530 is indeed a bi-color light with a temperature range of 3200K-5600K.
One thing I noticed is that the commands I was sending had `&on` or `&off` in them, this blocks the `brightness` and `temperature` parameter from being updated. Everything works as intended when this parameter is excluded.

I tested again to see if it could work without the preference file and without the on/off parameter included, but it did not. So the preference file is required.

**Comment by taburineagle** [comment]
Ah, excellent!  I'm glad to hear that it worked.  The reason why I asked if it was a bi-color light is that I do have logic in the main program that turns that feature on automatically for lights that are only bi-color lights, so now I can add the SNL530 to that list of lights.  I'm wondering if `SNL` is Neewer's code for bi-color lights - I might need to just add the "SNL" phrase as a trigger to turn that feature on.

I do have it so that `&on` and `&off`  at the moment override any other parameters from passing through, but I'll take a look at more properly implementing both those commands and a separate parameter at the same time down the line too.

**Comment by PrezP** [comment]
My light appears as NEEWER-SNL530 in the interface. Looking at their website, the last page of the [Neewer app manual](https://neewer.com/pages/en-instruction-for-neewer-lighting-control-system-app) has a table of lights, features and compatibility, though it's in a not-so-friendly image format.

**Comment by taburineagle** [comment]
**Ahh!!!**  Thanks for that, that's actually extremely helpful, I wasn't aware of that list!  So apparently all of the lights in the SRP, ZRP, SNL families, as well as the GL1 and NL140 are bi-color only lights.  Interesting... it _also_ lists which lights have group control and which ones don't, which is also helpful.  I'm not sure what "NEEWER INFINITY" is, but a lot of those ones listed above are Bluetooth controllable as well.

**Comment by taburineagle** [comment]
Hi @PrezP - I'm going to close this issue as it's been a while, and 0.12 _should_ address this issue (as it now loads the correct settings for the SNL530 on launch) - if you have any other issues, please let me know!
