### ISSUE TITLE
Enhancement- Trying to Connect to Lumia Streams to allow stream chat to control lights through commands

### ISSUE THREAD

**Issue by TheVOW** [taburineagle/NeewerLite-Python#37]
I have 0 experience in coding, and have spent the last 4 hours or so figuring out how your program works. Still haven't figured out how to start the program with the --http parameter, so I have been unable to connect the software to my streamdeck. I was hoping to use my Neewer lights for stream, and set it up where my chat can trigger specific colors and scenes through donations and channel points from twitch. I figured if I could connect to my Stream Deck, I could have Lumia trigger the effect when an alert is triggered, but I am stumped. Any advice would be great!

**Comment by taburineagle** [comment]
Hi @TheVOW - sorry you're having issues getting things to work!  A few questions, which platform are you currently running, Windows, MacOS, Ubuntu/Linux, or something headless like a Raspberry Pi system?  Also, are you getting any _specific errors_ in trying to get it to work (as in it launches, but the functionality isn't cooperating somewhere), or is it just not launching at all?  I need a bit more troubleshooting info to sort your specific problem out.  Make sure you're using Python 3, and have the Bleak and PySide2 Python packages (Bleak is required for Bluetooth connection to work, PySide2 is only really required if you plan to use the GUI.)  Launching the --http parameter from the command-line should just work with

`python3 (path to NeewerLite-Python) --http`

One problem you _may_ run in to with running in HTTP mode is the program boots and says everything is fine, but the server itself disallows your IP address from communicating and throws up a 403 Forbidden error.  By default, NeewerLite-Python's HTTP server only lets specific local IP addresses access the program itself, so if that's the case, you'll need to add your IP address to the allowed IPs that are allowed to access the server.  If that's the problem, the easiest way to fix it is through the GUI, but if you can't access the GUI, I can walk you through doing the same over the command line.

**Comment by fribse** [comment]
Hi @TheVOW
That is the exact setup I've done here.
I have it set up on a Rpi3, running in HTTP mode, and the stream deck is issuing http commands to it.
There is a good guide in the docs on setting it up on a RPi. You can of course also set it up on a PC, which platform are you using?

**Comment by taburineagle** [comment]
Hey @fribse - is everything still going well with your setup?  Ha, I've been in and out doing other projects in the past few weeks, I have to admit I haven't had a lot of time to tinker with NeewerLite-Python lately :/

**Comment by fribse** [comment]
Yes, for the current setup it's working perfectly 😉

**Comment by taburineagle** [comment]
Ah, excellent!

**Comment by TheVOW** [comment]
Still getting used to this site! Didn't realize I had received some responses, you guys are amazing! I am running a PC with Windows 10. When I try to run that command in my command prompt I get this message:

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I know I have Python, because I have been able to get the GUI to run.

**Comment by TheVOW** [comment]
I have Python, got Bleak installed, and got Pyside 2 installed. I am able to open and run the GUI and it has connected to my lights, but I still can't open the HTTP browser, and connect it to my Stream deck.

**Comment by taburineagle** [comment]
Sorry for the delay!  OK, so if you open a command prompt and just type in 

`python`

It gives you this error?:

> Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

A tip from [someone else on StackExchange](https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store) gives this possible tip - 

> 1. Check your Python version and be sure it is installed on your machine
> 
> 2. Check the path environment variable
> 
> 3. Go to -> "start" and type "Manage App Execution Aliases". Go to it and turn off "Python"

**Comment by TheVOW** [comment]
Gotcha, I downloaded Python from the windows store and that seems to have fixed the problem. Now I get this message

python3: can't open file 'C:\\Users\\Will Powers\\(path': [Errno 2] No such file or directory

Do I need to reinstall bleak now that I have downloaded Python from another source, or is it that my downloaded file NeewerLite - Python is still in my download folder?

**Comment by taburineagle** [comment]
What was the path you used?  Ahh, I think I see what you mean - when I said 

`(path to NeewerLite-Python)`

I mean to insert the path you currently have set where you have NeewerLite-Python stored - so it would be something like (this example would work if you have the .py file in your Downloads directory):

`python3 'C:\Users\Will Powers\Downloads\NeewerLite-Python.py' --http`

**Comment by taburineagle** [comment]
Hi @TheVOW - I'm going to close this as it's been a while and I haven't heard anything lately... please feel free to reopen if you still have issues!
