### ISSUE TITLE
After switching to 0.12 it does not apply the 'presets' until I go to the browser and do a few refreshes?

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#41]
I have the setup on RPi as you might know,
With the current version 0.12 if I click the 'preset' in the webpage, it doesn't apply it until I refresh the page af few times, the same happens with the URL I use in streamdeck?

**Comment by taburineagle** [comment]
That also shouldn't be... 0.12 isn't really ready for "primetime" yet, but the logic to loading presets hasn't changed.  Hmmm...

**Comment by taburineagle** [comment]
Just quickly testing the HTTP server out here (which is just putting the lights I have near the PC (SL80, RGB660 and SNL660) and running the latest 0.12 code), I personally don't notice any issues with presets.

**Comment by fribse** [comment]
Very odd, it shouldn't be because I'm using firefox, as it's from my streamdeck, but it could of course just be a network problem.

**Comment by taburineagle** [comment]
Yeah, it shouldn't be a browser problem - I've used several different browsers in the past and they all behaved the same - except for Chrome (for some reason it sent every request twice, it's how Chrome is wired), but I fixed that a few months ago.  It could be a network issue, or maybe one of the lights is slowing the other ones down - that happens sometimes when the connection is slower to one over the others.

**Comment by taburineagle** [comment]
I'm also curious - does the NeewerLite-Python console list the commands being sent when they don't work?  I wonder if it's a cache thing, like the browser says "we already _loaded_ this, we don't need to do it again" or something along those lines.  It should show something along the lines of

```
127.0.0.1 - - [19/Jun/2022 22:31:34] "GET /NeewerLite-Python/doAction?use_preset=1 HTTP/1.1" 200 -
[22:31:34] - Processing HTTP arguments
```

when they go through (this command was for Preset # 1)

**Comment by fribse** [comment]
Hmm, didn't get a notice that you replied :-D
How do I get the log shown, can't remember?

**Comment by taburineagle** [comment]
Ah, ha, and I didn't get a notification about your reply either... interesting GitHub 🙄  @fribse Sorry for the delay!  If you run NeewerLite-Python from the command-line instead of the service (stop the service first, `sudo systemctl stop neewerlite-python`, then run the command the service would be running on the command line itself, something like `python3 /opt/NeewerLite-Python/NeewerLite-Python.py --http`), you should get the log to output status messages as it would if you were running the GUI version.

**Comment by taburineagle** [comment]
That's weird... I still think it's a page caching issue, like the browser that's loading the page loads the data from the last time the page loaded, instead of re-sending it to NLP's HTTP server.  That's one reason I was curious if the commands themselves were being shown in the console, because that would prove NLP is at least receiving the commands when it acts up.

**Comment by fribse** [comment]
Hi @taburineagle 
I finally caught it. So I've been recording videos all day long.
I also turned the lights on and off several times, suddenly it doesn't finish the job, and I have to go to the webpage to do a refresh.
So the log looks like this when I select preset 2 which is the 'on' mode:

```
10.11.12.33 - - [27/Aug/2022 21:20:20] "GET /NeewerLite-Python/doAction?use_preset=2 HTTP/1.1" 200 -
[21:20:20] - Processing HTTP arguments
[21:20:20] - Going into send mode
```

But I don't see ANYTHING for the turning off (preset 1) until I do a refresh, and then the 'sender' of the request is not the automations, but my workstation:
```
10.11.12.40 - - [27/Aug/2022 21:24:39] "GET /NeewerLite-Python/doAction?use_preset=1 HTTP/1.1" 200 -
[21:24:39] - Processing HTTP arguments
[21:24:39] - Going into send mode

```

**Comment by taburineagle** [comment]
_Huh_ - interesting!  I'll have to check more into this!  It _could_ be one of the links is a bit slow and making everything else slow with it, but I'm not 100% on that one.

**Comment by taburineagle** [comment]
Hey @fribse - long time no write... I did add a change to the HTTP server in the latest release that ensures commands aren't cached (or at least ensures _webpages_ aren't cached, the Pragma:No-Cache settings and related are sent as headers), so I'm curious if that solves this problem, or if this could be related to something else (lack of communication with one of the lights, etc.)

**Comment by fribse** [comment]
I haven't seen the problem for a long time, so I guess it's fixed :-)
