### ISSUE TITLE
Current code fails to start GUI?

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#5]
I don't see a version string (whoops), but the code currently available shows this when I try to start the GUI:

```
D:\neewer>python NeewerLite-Python.py
Traceback (most recent call last):
  File "D:\neewer\NeewerLite-Python.py", line 1284, in <module>
    mainWindow = MainWindow()
  File "D:\neewer\NeewerLite-Python.py", line 84, in __init__
    self.connectMe() # connect the function handlers to the widgets
  File "D:\neewer\NeewerLite-Python.py", line 103, in connectMe
    self.Slider_HSL_1_H.valueChanged.connect(self.computeValueHSL)
AttributeError: 'MainWindow' object has no attribute 'Slider_HSL_1_H'

```

**Comment by taburineagle** [comment]
Ah, I know what's happening on this one - I changed "HSL" to "HSI" (as that's the proper name for that mode), but the function is still looking for self.computeValue**HSL** - I'll fix this one ASAP as I have access to my coding computer.

**Comment by taburineagle** [comment]
Actually, I think the problem with this one is the version of NeewerLite-Python.py you're using isn't the same version as the ui_NeewerLightUI.py file you're using (the newer one names that attribute as _Slider_HSI_1_H_, which is correct.)  Both of those files have had some changes to fix the HSL/HSI naming situation.

**Comment by fribse** [comment]
Douh, you are absolutely right, I thought I had it updated, oh well, after updating BOTH files, it works perfectly.
I can even turn the light on and off (which I couldn't get to work in the old code).
So far it connects every time with this version.
