### ISSUE TITLE
RGB530 not found

### ISSUE THREAD

**Issue by craigjmidwinter** [taburineagle/NeewerLite-Python#55]
Not sure if this is related to these specific lights, but they work in the app and show up as bluetooth devices when I scan for devices in my system settings but the cli says it did not find any neewer lights

**Comment by taburineagle** [comment]
Hmm, interesting - do you get the same result with the GUI?  Also, might be a long shot, but if you still have the phone app (or another service) connected/paired to the lights, NeewerLite-Python won't be able to see them.

**Comment by taburineagle** [comment]
I'm closing this for now, as I haven't heard any other issues in a bit over a week - if you keep having issues, please feel free to re-open it!
