### ISSUE TITLE
Can't get lights to detect in the UI

### ISSUE THREAD

**Issue by StriderStone** [taburineagle/NeewerLite-Python#58]
Hello,
I have a ROG crosshair viii dark hero motherboard.
my LMP shows 11.9457 which is Bluetooth Core Specification Version 5.2 which SHOULD have BLE enabled.
For some reason I am unable to get my lights detect in the UI.
I have the Neewer app installed on my phone and the lights show up just fine on there.
I have Bluetooth enabled on my computer as well, but I don't even see the lights when I am searching for new devices there.
I turned off the light and turned it back on and the bluetooth icon is currently blinking, I assume that means it's in pairing mode, but I am not sure exactly.
Does anyone have any ideas?

EDIT: The 4 lights that I have are Neewer 660 RGB

**Comment by fribse** [comment]
I'm not an expert, but I've had a lot of challenges with BT radios, some works, some dont. I know it's not much help, I have mine setup through a RPi, so maybe test with such a beast?

**Comment by Desaydrone** [comment]
I got the same thing, i realise that in the bluetooth on my pc the light disconnect quickly from the bluetooth, so can't use it, i have to try with other dongle

**Comment by taburineagle** [comment]
Hi @StriderStone  and @Desaydrone - I got an e-mail a few weeks back where someone had the same issue that you're describing, using a TUF Gaming X570-Plus and Windows 10 PRO 21H2.  If your OS can't see the lights, then NeewerLite-Python also can't - it could possibly be a signal issue, do you have the antennas hooked to the WiFi/Bluetooth ports on the back of the mobo?  In the case from a few weeks ago, their WiFi antenna was not attached, and that antenna also apparently carried the Bluetooth signal:

> Got things working!
> A friend who knows python was helping me test/debug.
> Turns out my mobo's wifi antenna also carries the bluetooth signal, wasn't attached prior..
> 

Another possibility is you might still have the lights connected to the Neewer app on your phone, which would give you issues in _linking_ to the lights, but they should still show up as Bluetooth devices in Windows.

**Comment by taburineagle** [comment]
I do know that the 660s work with NeewerLite-Python, as those are the kinds of lights I have (well, 660SNL and 660PRO) and they both work... but again if the OS can't see it, or something else is currently linked to the light (blinking light is definitely a good sign, that does mean that it's not currently paired with another app/controller) you'll have issues getting it linked in the program.

**Comment by StriderStone** [comment]
I didn't even know there was a wifi antenna..........I will have to see if I have it. lol

**Comment by taburineagle** [comment]
Hopefully that works :)  Yeah, I think the Raspberry Pi is the same way, where both the WiFi and BT signals/antennas go to the same chip, so that's a good place to start.

**Comment by taburineagle** [comment]
Hey @StriderStone - I'm going to close this one as I haven't heard anything in a week - feel free to reopen it if you have issues!

**Comment by StriderStone** [comment]
that fixed it. Thanks for the help everyone.

**Comment by taburineagle** [comment]
Ah, brilliant!  You're welcome!
