### ISSUE TITLE
Enhancement request: The 'on' 'off' should be seperate from CCT/HCI/...

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#6]
It seems kind of illogical that the power controls are on the CCT page, that should be seperately available (IMHO).
It's a bit silly to set it to white to turn it off 😆

**Comment by taburineagle** [comment]
Ha, true, true 😅  I put it on that tab because all the lights can use CCT mode so far, but only the RGB ones can use the HSI/SCENE modes...  Definitely worth looking into for a later version!

**Comment by taburineagle** [comment]
Ha, @fribse - finally, _finally_... I've done it 😅  I want to kick the tires completely on this before commiting (as the actual featureset with this commit adds a lot more than just the repositioned buttons), but this is how the new layout is going to look - 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/18430526/147820704-171e7004-3091-4c4c-853d-0fc6c2bdedc9.png">

**Comment by fribse** [comment]
You ARE a star!

**Comment by taburineagle** [comment]
😀🦝🌟
