### ISSUE TITLE
Difficulty Discovering and Linking to lights

### ISSUE THREAD

**Issue by markvrepo** [taburineagle/NeewerLite-Python#62]
I'm using one of the approved bluetooth dongles with 3 neewers RGB/CCT lights.  I find the http service has a hard time finding one and occasionally two of the lights and, once found, linking can take quite a few retries.

There is some signal level information in the web page.  What are reasonable numbers ?  I am seeing in the low to high -80s.

**Comment by fribse** [comment]
I would say -60 is a good signal, I can connect often with -70, but I don't think I will get a connection with -80.

**Comment by markvrepo** [comment]
Thanks.  Looks like I need to distance my bluetooth dongle from my pc.

**Comment by markvrepo** [comment]
Would you mind letting me know which bluetooth dongle you are using ?  I'm
using the tplink that has been recommended.  I ran a usb extender as a
result of your prior email and I still have a light a mere 8 feet away that
is running -80.  The rest of the lights dropped into the low 70s, so that
is appreciated.

**Comment by taburineagle** [comment]
Hi @markvrepo - sorry for the delay, ha, been working on tweaking a PC I just built :)  Yeah, usually I'd say the sweet spot would be somewhere in the -60 to -40 range for mid-range signal level.  -80 is a really low signal level for these lights, you may get a connection to them, but they aren't guaranteed to stay connected for any period of time with a level that low, and if you do, the communication will be slower from NeewerLite-Python to multiple lights.  I personally use one of these Bluetooth dongles with my setup - [https://www.amazon.com/gp/product/B07V1SZCY6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1](https://www.amazon.com/gp/product/B07V1SZCY6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

**Comment by taburineagle** [comment]
Hi @markvrepo - I'm going to close this one as I haven't heard back in a while.  If you still have issues, feel free to re-open it!
