### ISSUE TITLE
Search doesn't find any lights

### ISSUE THREAD

**Issue by jtbiddle** [taburineagle/NeewerLite-Python#67]
Hey, sorry to open a relatively vague issue but I would love to get this software to work. I have it installed and it seems to run fine except no lights are found. 

I have tried it with the built-in bluetooth on my desktop and the recommended TP-Link UB400 adapter (with the desktop adapter disabled). My light is a RGB660 about eight feet from the PC, and the bluetooth indicator is flashing on the light. My phone connects to it with the official app. Other bluetooth devices are listed when do the Windows scan with the UB400. 

The program gives me the following output: 
```V:\Work\Lights\NeewerLite-Python-0.12d>python NeewerLite-Python.py
---------------------------------------------------------
             NeewerLite-Python ver. 0.12d
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
qt.qpa.fonts: Unable to enumerate family ' "Ubuntu Mono derivative Powerline" '
[22:48:03] - Searching for new lights
[22:48:11] - Background Thread Running
[22:48:14] - Background Thread Running
```

I assume that the deprecated function and missing font aren't relevant, but I'm not positive. 

This is the output with --list:
```V:\Work\Lights\NeewerLite-Python-0.12d>python NeewerLite-Python.py --list
---------------------------------------------------------
             NeewerLite-Python ver. 0.12d
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
NeewerLite-Python 0.12d by Zach Glenwright
Searching for nearby Neewer lights...
We did not find any Neewer lights on the last search.
```

I know some people only have lights show up intermittently, but I have tried it dozens of times. Are there any other troubleshooting steps I can try?

**Comment by taburineagle** [comment]
Hi @jtbiddle - do you see the lights listed in Windows's Bluetooth listing?  If Windows can't see it, NeewerLite-Python can't see it either.  The lights' Bluetooth signal isn't the best, so it might be out of range from where you have it.

**Comment by taburineagle** [comment]
Hi @jtbiddle - I'm going to close this one as I haven't heard back in a while - if you continue to have issues, please feel free to open a new ticket!
