### ISSUE TITLE
Adding Midi-Support to the script?

### ISSUE THREAD

**Issue by mxtives** [taburineagle/NeewerLite-Python#69]
Hey,

my name is Robin and I am totally new to github and I don't have any clue when it comes to programming but know a thing or two about MIDI. I am currently looking into a budget friendly alternative to DMX controlled lights and thought that the NEEWER Lights (which I already bought a while back) would be a nice fit to my problem and my band's light show and therefore awesome stage presence.

I stumbled across this thread:
https://discuss.cakewalk.com/index.php?/topic/56390-midi-to-neewer-lights/

which I thought would have the solution only to discover that it is not a thing (yet).

To clarify what I mean in the Issue-Headline, is there a way to:

- add MIDI-Support to the script (meaning that the script receives MIDI Input/Control Messages which I send via my DAW)
- add parameter-controls to brightness, hue, custom scene-loading (which I then control via MIDI)
(- add a vst instance (if needed?) to directly link the MIDI information to the script)

I hope this is helpful.

Sincerly,

Robin

**Comment by taburineagle** [comment]
Ah!  Hi Robin @mxtives - interesting question... I checked the thread out too and saw it was just recently posted last week.  It should be somewhat simple to convert MIDI messages to NeewerLite-Python commands, although I have to admit, besides doing a little bit of synthesizer tinkering, I'm fairly clueless on the MIDI spec personally.  I do see Python does have MIDI libraries available, like [MIDO](https://mido.readthedocs.io/en/latest/), so it should be possible.

**Comment by taburineagle** [comment]
I'm closing this for now, I don't really have any MIDI integration planned (at least at the moment), but I'll let you know if I do down the road!
