### ISSUE TITLE
Feature - A/B presets

### ISSUE THREAD

**Issue by mungewell** [taburineagle/NeewerLite-Python#70]
Just got a couple Neewer lights (RGB176) and confirmed that they can be controlled by this script. The official Android App has a "1" and "2" preset function, allow fast switching between two settings. 

Are the two presets stored on the lights and is it possible to add this function?

**Comment by mungewell** [comment]
to clarify I am using the '--cli' mode... as I don't have QT installed.

**Comment by taburineagle** [comment]
Hi @mungewell - sorry for such a **long** delay in responding!  The presets on the GUI labeled 1 through 8 (in the middle) are for A/B presets like you described.  You can store a specific set of settings (like 1 can be off entirely, 2 can be 100% red, and 3 can be 100% blue) and jump between them by clicking those buttons.

<img width="590" alt="Screenshot 2023-11-14 at 8 29 31 AM" src="https://github.com/taburineagle/NeewerLite-Python/assets/18430526/c1c2e1f0-a208-4034-86c2-1aa83709a1c1">
