### ISSUE TITLE
Is it possible to use this to set up “if this then that” commands via Loupedeck?

### ISSUE THREAD

**Issue by montaemontana** [taburineagle/NeewerLite-Python#72]
Forgive my ignorance, I’ve never used Python but I’m a fast learner. My goal is to have my lights change according to chat alerts. I’m using an M1 iMac with a Loupedeck, I want to control two RGB panels and a CB60 if I can.

**Comment by fribse** [comment]
As the product is local only, there is no ifttt integration, but you can send http commands to it, so you could set up something locally that could send http command, and listen to ifttt

**Comment by montaemontana** [comment]
> As the product is local only, there is no ifttt integration, but you can send http commands to it, so you could set up something locally that could send http command, and listen to ifttt

Thank you for your response. Once I saw that this allows you to create an http server I figured something had to be possible. Do you know of any resources that thoroughly explain how it’s do me by any chance

**Comment by fribse** [comment]
I've set it up on my streamdeck. I've made two presets, one for the 'off', and one where the lights are set as I want them. I've then integrated the lights to Home Assistant with the HTTP commands, and then I toggle the 'studio' lights via the Home Assistant integration in Streamdeck.
You should be able to just do HTTP calls directly from the deck as well.
