### ISSUE TITLE
SL-90 not working

### ISSUE THREAD

**Issue by ssantus** [taburineagle/NeewerLite-Python#74]
Hi, I have found a couple of compatibility issues when trying to connect to my SL-90 light. 

The first one is that bleak will not show my device when scanning. This one was easy to solve by checking that the list of devices is filtered by name looking at "NEEWER" in the device name. However, my light's name is "NW...", adding that option to the device name check logic fixes the issue.

The second one comes after connecting to my light. I am only able to turn it on and off, trying to change between modes, brightness or scenes won't change anything in the light. Both using the GUI or http server.

Do you have any pointers or ideas why it might not be working?

**Comment by taburineagle** [comment]
Hi @ssantus  - sorry for the delay, I've been out for the past week.  One thing I'd check is the Light Preferences tab - connect to the light, select the "Light Preferences" tab, and check and make sure "This light can only use CCT mode" is _not_ turned on.  If it is, turn it off and click "Save Preferences" - then it _should_ work.  The reason for this is that Neewer RGB and Two-tone lights send their commands in different ways, and the SL-90 looks to be an RGB light.  If NeewerLite-Python has the option turned on to only use CCT mode on an RGB light, it's not going to send the commands correctly.

**Comment by ssantus** [comment]
Hi @taburineagle, thank you for getting back to me. I've followed your suggestion and checked the "Light Preferences" tab. I can confirm that the "This light can only use CCT mode" option was already disabled. Despite this, I'm still facing the issue. I can only turn the light on and off, and I'm unable to change any other option. 
I am not sure I understand the bluetooth communication of these lights, it is my first time working with something like this, but maybe the hard-coded ID's or commands have changed? .e.g. 
`setLightUUID = "69400002-B5A3-F393-E0A9-E50E24DCCA99" # the UUID to send information to the light
notifyLightUUID = "69400003-B5A3-F393-E0A9-E50E24DCCA99" # the UUID for notify callbacks from the light
`
The reason why I am asking is because I want to write a short program that turns my light on/off and changes color on a schedule.
Do you have any other suggestions or troubleshooting steps I can try?

**Comment by taburineagle** [comment]
Got you - yeah, the way the Bluetooth commands work is they send messages to those UUIDs, although the actual command being _sent_ to those paths might have changed...  Ha, I wish I could just rent all of the newer lights they put out so I can compare the system they use!  I'll need to pick one of those up at some point to compare the commands against the current system.  A few months back, someone posted a list of all of the Neewer lights at the time, and the command scheme they use, and I know a few of them use something called "Infinity" that I need to look into more (I think that's a new control scheme, but I'm not sure if it works without their app).  Actually, when I search for that light, the description even mentions "Infinity" - so I definitely think something changed under the hood there...
![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/9ba9e5e1-21d9-4df1-9084-5bdbfad1e7bd)

**Comment by taburineagle** [comment]
Ha, well...... I ordered an SL90 😁  So I'll report back when I see how it communicates with the Neewer app via Bluetooth.

**Comment by ssantus** [comment]
That is awesome! Let me know if I can help you with testing something.

**Comment by taburineagle** [comment]
Will do!  I received it this afternoon - now to see what it's sending to the official app...

**Comment by taburineagle** [comment]
Oh _wow_, there is a lot more going on under the hood with the SL90 compared to the SL-80 😄  I'm going to have to research this further!  It sends the base command NeewerLite-Python is sending it, but there are about 10 other things added to that command compared to what NL-P is sending out!

**Comment by taburineagle** [comment]
OK, update - I have HSI mode working on the SL-90 - will work on also getting CCT mode sorted this weekend if I get the chance to!  The main difference in CCT mode compared to the old Neewer models is it has something labeled "GM" that the old ones didn't (a slight color temperature adjustment?), so I need to look into what that does.  I haven't pushed a commit for the fix yet, but I will do that also in the next few days.

**Comment by ssantus** [comment]
Wow! Yes indeed, the "GM" is a feature that allows for Green-Magenta control of the light color (there is a bit of info about this in their [website](https://neewer.com/products/neewer-sl90-12w-on-camera-rgb-panel-video-light-66600927). Thanks for the update! Looking forward to test your fix :smiley:

**Comment by taburineagle** [comment]
Ah, OK, that makes sense - I tweaked the GM control in the iOS Neewer app and did indeed see green/magenta LEDs turn on in the light, so that's interesting!  I don't have the GM controls controllable yet, but HSI and CCT modes work - I also tried them with 3 other lights at the same time (so a SL90 Pro, SL-80, SNL660 and RGB660) and all 4 controlled well with this new update.  I don't have it pushed to the main branch yet, but here is the update from the WIP branch.  Replace the NeewerLite-Python.py file in your local directory with this one:

[https://github.com/taburineagle/NeewerLite-Python/raw/WIP-addInfinityLights/NeewerLite-Python.py](https://github.com/taburineagle/NeewerLite-Python/raw/WIP-addInfinityLights/NeewerLite-Python.py)

**Comment by ssantus** [comment]
I just tried using the new .py file for controlling my light. With this file, I can connect to my light and can turn it on and off without any issues. However, I'm still facing the same issues as before: I'm unable to send commands in both CCT and HSI modes. I tried to control the light using both the GUI and CLI options, but no luck using any method. This is what I see in the console: 

`Command: python3 ./NeewerLite-Python.py --cli --light=XX:XX:XX:XX:XX:XX --mode=cct --temp=3000
---------------------------------------------------------
             NeewerLite-Python ver. 0.14
                 by Zach Glenwright
  > https://github.com/taburineagle/NeewerLite-Python <
---------------------------------------------------------
[21:30:29] - Starting program with command-line arguments
[21:30:29] -  >> --temp (30) isn't between the bounds of 32 and 85, so falling back to closest boundary of 32
[21:30:29] -  > Launch GUI: False
[21:30:29] -  > Show Debug Strings on Console: True
[21:30:29] -  > Mode: CCT
[21:30:29] -  > Color Temperature: 3200K
[21:30:29] -  > Brightness: 100
[21:30:29] - -------------------------------------------------------------------------------------
[21:30:29] -  > CLI >> MAC Address of light to send command to: XX:XX:XX:XX:XX:XX
[21:30:29] - A custom preferences file was found for XX:XX:XX:XX:XX:XX!
[21:30:29] -  > CLI >> Bytestring to send to light: 0x78 0x87 0x2 0x64 0x20 0x85
[21:30:29] - -------------------------------------------------------------------------------------
[21:30:29] -  > CLI >> Attempting to connect to light (attempt 1 of 6)
[21:30:29] - -------------------------------------------------------------------------------------
[21:30:29] - Attempting to link to light [NW-20200037&FFFFFFFF] MAC Address: XX:XX:XX:XX:XX:XX (Attempt 1 of 6)
[21:30:31] - Successful link on light [NW-20200037&FFFFFFFF] MAC Address: XX:XX:XX:XX:XX:XX
[21:30:31] - -------------------------------------------------------------------------------------
[21:30:31] -  > CLI >> Attempting to write to light (attempt 1 of 6)
[21:30:31] - -------------------------------------------------------------------------------------
[21:30:31] - Going into send mode
[21:30:31] - -------------------------------------------------------------------------------------
[21:30:31] -  > CLI >> Attempting to disconnect from light (attempt 1 of 6)
[21:30:31] - -------------------------------------------------------------------------------------
[21:30:33] - Successfully unlinked from light 1 [NW-20200037&FFFFFFFF] MAC Address: XX:XX:XX:XX:XX:XX
`
I cannot find any errors in the debug log. Do you have any suggestions on where to look at?

Thanks for your support!

**Comment by taburineagle** [comment]
Interesting, I'm not sure if we have the same kind of light, but I think I know what's happening - my light is listed as NW-**20220057**&FFFFFFFFF, or an SL-90 _PRO_ - I didn't know there were 2 different versions of the SL-90... but I think they use the same protocol, so it should still be good.  I'm adding a new entry for the NW-20200037 as the "SL90" and I added the Infinity flag to that light as well.  Also, I don't have CLI mode working with the Infinity protocol quite yet - just the GUI.

I pushed the commit adding the NW-20200037 - let me know if this one works.  You should also be able to delete the custom name for the light as well, the new device detection logic should be able to find NW- prefixed lights.

[https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py)

**Comment by taburineagle** [comment]
**UPDATE** - I also fixed the CLI interface, so that should also be working with Infinity lights now (or at least the SL90 and SL90 Pro)

**Comment by ssantus** [comment]
Awesome! Both CCT and HSI controls work now on my SL-90 (GUI and CLI) :smiley: . 
P.S. Scenes do not work though.

Thanks a lot for your help!

**Comment by taburineagle** [comment]
Ah, excellent!  Glad to hear that - I also just now pushed a commit that added GM adjustment to the CCT tab for Infinity lights.  _Yeah_, it's going to take a **lot** more to get Scene working on the Infinity lights.  The original set of lights had 9 pre-defined effects with only a brightness adjustment, but the Infinity ones have a _lot_ more to adjust, each effect having a different set of parameters, so that's going to need a lot more planning and coding to get that squared away before it's ready.

**Comment by taburineagle** [comment]
If you want to test out the GM adjustment, you're going to need to replace both NeewerLite-Python.py and ui_NeewerLiteUI.py as I did change a few GUI elements in that update.

[https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py)
[https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/ui_NeewerLightUI.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/ui_NeewerLightUI.py)

**Comment by taburineagle** [comment]
OK, @ssantus - over the past 2 weeks on and off, I've been tweaking a _lot_ overall to make Scene/FX work.  I re-wrote all of the GUI elements completely (which helps out considerably when building the FX pages), set up each individual effect to have its own parameters page, and as of 10 minutes ago, wired all of that logic into making scenes work... and they all do.  I don't have a commit yet, because I want to test _everything_ out, and I have 3 special color boxes I still need to make for 3 separate effects, but I'm getting close.

**Comment by taburineagle** [comment]
OK, **huge** commit just pushed to the WIP branch (it's not 100% ready for complete release yet, but the functionality is there) - this commit adds support for scenes on Infinity lights, and redesigns a lot of the GUI elements to play more nicely with the changes that needed to be made to add all of the custom parameters to Infinity scene presets.   If you'd like to try this one out @ssantus, download the latest versions of the .py files below (I'd suggest to an alternate directory, as this is a Beta version) and then run that version of NeewerLite-Python.py.

Here are the latest WIP versions - you need to download _both_ of them for the new version to work.
[https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinityLights/NeewerLite-Python.py)
[https://github.com/taburineagle/NeewerLite-Python/blob/WIP-addInfinityLights/ui_NeewerLightUI.py](https://github.com/taburineagle/NeewerLite-Python/blob/WIP-addInfinityLights/ui_NeewerLightUI.py)

**Comment by taburineagle** [comment]
OK @ssantus  - I am getting ready to release the next version of NeewerLite-Python shortly - it has Infinity support, as well as support for effects, sending to both "normal" (old) command set lights and Infinity lights in tandem, and a bunch of other upgrades.  I will let you know when I have published it.

**Comment by taburineagle** [comment]
@ssantus - Update: I'm planning on releasing the next version shortly (I said that before, but I mean "this week" shortly) - I'm closing this for now, because I haven't heard anything from you about it in a while.  Feel free to open another Issue if you notice anything else (or if the new version still doesn't work with the SL-90)
