### ISSUE TITLE
Preset Animations dont seem to be working on the CL124

### ISSUE THREAD

**Issue by mrben1985** [taburineagle/NeewerLite-Python#79]
So when I cycle through the preset scenes on the CL124 it does not seem to make any effort to change them. It will put it into Anim mode but it will play last animation set on the device and does not process any further scene requests.

**Comment by taburineagle** [comment]
Hi @mrben1985 - I don't physically have a CL124 in front of me to test, but in looking it up, it seems like it uses the new Infinity command set, which is slightly different with FX presets (17 of them as opposed to 9 in the original light command set - although I could be wrong in this, but again, I don't physically have one to test with at the moment).  I'm working on releasing the new version of NeewerLite-Python that _can_ do that command set (hopefully sometime this week), so hopefully once I have that live, it will work correctly with the CL124.

**Comment by mrben1985** [comment]
It looks like you are right! I found the other branch late last night so didn't get a chance to test it. 

Awesome stuff thank you for all your work on it.

**Comment by mrben1985** [comment]
Let me know when you have a release candidate will be more than happy to test it.

**Comment by taburineagle** [comment]
Excellent!  Technically the latest separate branch is the next release candidate, I just wanted to fix one little thing, which I just did with the latest commit, and I set CL124 lights as Infinity command set lights.  I will merge that branch back into the main branch now!

**Comment by taburineagle** [comment]
OK, I've merged the Infinity branch back into main.  To test the release candidate, I'd suggest making a new folder or VM, downloading the [NeewerLite-Python.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/main/NeewerLite-Python.py) and [ui_NeewerLightUI.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/main/ui_NeewerLightUI.py) files into that folder, and running it from there.

**Comment by mrben1985** [comment]
I have given it a go, sadly not getting any life out of the device when it is sent commands. The GL1 Pro is still responding fine. So legacy controls seem to be ok. It looks like it is connected to the device because any changes I make on the light itself are reported back in the status. Just anything applied from the GUI changes seem to do nothing. Let me know if I can help anyway with debugging. 

Help is much appreciated.

**Comment by mrben1985** [comment]
[17:01:14] - Going into send mode
NeewerLite-Python.py:2910: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(0.05)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
NeewerLite-Python.py:2912: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(0.05)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Is the only output in the debugger so far.

**Comment by taburineagle** [comment]
_Hmmmm_, interesting - well, that means they're definitely not Infinity lights at least, so that's a little closer 😊   That error you got is because I added a quick power-cycle for Infinity lights to sync up with FX parameters, but your light _isn't_ an Infinity light.

2 questions for you:

- Did the original program (before the release candidate) control the lights fine in CCT and HSI mode? 
- Do any of the FX work at all with the original program?  Specifically the first 9?

If either of those are the case, then this light uses a different control scheme (or a modified version of the "normal" control scheme) and definitely not an Infinity one (as CCT and HSI wouldn't work in the original program if it were using the Infinity control set).

**Comment by mrben1985** [comment]
So the original did work in the CCT and HSI mode and when it triggered an Anim it would play the last selected on the physical device. Not the one selected in the UI. 

It has the 17 animations like the infinity lights. Which is why I first suspected it would fall into this category. 

So looks like its a hybrid.

**Comment by taburineagle** [comment]
Very interesting - 2 more questions:

- Is this the CL124 RGB, or CL124 Pro?
- If you load an FX in the original program, then change the brightness value, does that do anything?  I'm assuming no, but I'm trying to rule out potential issues.

**Comment by mrben1985** [comment]
It is a CL124 RGB, 

The brightness slider has no effect in Anim mode.

**Comment by mrben1985** [comment]
Awesome stuff, I will stick with the old release for now. Least I can use one preset animation :) 

Thanks for all your work!

**Comment by taburineagle** [comment]
You're welcome - I'll let you know what I find when I get one!

**Comment by taburineagle** [comment]
OK @mrben1985... I got it!  First impressions:

- It's... _much_ bigger than I thought it would be 😊  I thought it was just a little hand-held wand light!
- The protocol difference is exactly what I thought it would be - it's sending Infinity protocol, but with one very important omission - here's a chart I made a few months back showing what Infinity is being sent from FX mode:

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/3f1afff3-d150-4225-aaa6-07338f3aa4e1)

What the CL124 does is send all of the same information  _except_ what's in the grey section (which is basically an "Infinity" mode identifier and the entire MAC address of that particular light), so it's sending an Infinity-esque protocol, but without the Infinity information.  Neewer like I said, definitely re-invented the wheel for this one... it _is_, but it _isn't_ - but at least with that information, I know what's going on.

**Comment by mrben1985** [comment]
Awesome stuff, I did not expect you would grab one so quickly.

I am overall quite impressed with it. Kids love it also.  Glad you got to the bottom of the protocol. Do you have a PayPal or something I can send you some cash to? Least I can do is buy you a beer or a coffee.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by taburineagle** [comment]
Ah, thank you very much!  I appreciate that - I do have a PayPal, the address is (written to deter scambots)

`h m s u a m z g (at) c o m c a s t (dot) n e t`

I'm still trying to find the best way to implement that "Infinity-esque" logic into the normal light logic, but I have a plan.  Yeah, not a bad light overall - I could see interesting effects from using it!

**Comment by mrben1985** [comment]
Awesome, look forward to seeing the next release. 

Cheers for all the work so far and enjoy the beer.

**Comment by taburineagle** [comment]
Brilliant, thank you very much, I definitely appreciate it! 😊  OK, I have the Infinity-esque protocol working on all modes and I'm going to push a testable release candidate, which will be available on the WIP-addInfinity-esque branch (to try it, download the [NeewerLite-Python.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinity-esque/NeewerLite-Python.py) and [ui_NeewerLightUI.py](https://raw.githubusercontent.com/taburineagle/NeewerLite-Python/WIP-addInfinity-esque/ui_NeewerLightUI.py) files from that branch).  I still have a few things I want to work out before making the changes permanent (global presets aren't behaving nicely with that new protocol yet, for example) so I have to look into those before pushing the changes back to the main branch.

**Comment by mrben1985** [comment]
The FX change looks to be working great. Thank you!

**Comment by taburineagle** [comment]
Excellent - I made one more quick GUI correction and merged that side branch back into the main branch, so that should be sorted out!  So I'm closing this one, feel free to open another one if you have any other issues!
