### ISSUE TITLE
Feature Request: Add option to CLI to scan/list available lights

### ISSUE THREAD

**Issue by DanielBaulig** [taburineagle/NeewerLite-Python#8]
It would be useful to be able to scan/list available list through the CLI.
Without the GUI there does not appear to be a way to obtain the mac addresses of available lights otherwise.

**Comment by taburineagle** [comment]
Ah, yes, good point - you can with the HTTP server, but it would make sense to implement a scan in CLI mode as well... I'll take a look at that when I get a chance to, hopefully over the weekend.

**Comment by taburineagle** [comment]
OK, this feature has been added - to query the program from lights on the CLI, all you need is the `--list` command (you don't need `--cli --list`, _just_ `--list`), and the program will print out a CLI-formatted table of the lights found by the program, that looks like this:

```
NeewerLite-Python 0.5a by Zach Glenwright
Searching for nearby Neewer lights...

We found 2 Neewer lights on the last search.

Custom Name (Light Type)                                       MAC Address
-------------------------------------------------------------- -----------------
(NEEWER-RGB660 PRO)                                            CD:B8:B4:15:C3:8D
(NEEWER-SL80)                                                  F2:55:41:56:1D:A7
```

**Comment by taburineagle** [comment]
@DanielBaulig - Hello!  I'm going to close this issue for now because it's been a week, the feature has been added since the issue was raised.  If you have any issues with the CLI list, please feel free to reopen the issue.

**Comment by DanielBaulig** [comment]
Awesome, thank you! Sorry, been a little busy last couple of days. Greatly appreciate this.

**Comment by taburineagle** [comment]
You're welcome!  I've been busy myself this week, so I know what you mean! 😊
