### ISSUE TITLE
Presets gone after updating files?

### ISSUE THREAD

**Issue by fribse** [taburineagle/NeewerLite-Python#81]
Hi Glenn
I'm really happy with the setup here, with the neewlights and your service, it's working nicely here.
I just upgraded the two files for my webserver, the Neewerlite-Python.py and ui_Neewerlite-Python.py, I haven't done that for ages.
Previously I saw a grid of presets, now I only see 1, and it seems to be empty? (4 of them are not linked, as I'm doing this remote, and I probably need to powercycle the lights for them to be able to pair).
![billede](https://github.com/taburineagle/NeewerLite-Python/assets/13660621/8b51816b-5897-43f2-b408-a6c7ca2fa8c0)
Looking at the server I still see files though:
![billede](https://github.com/taburineagle/NeewerLite-Python/assets/13660621/a02201ed-7904-4cee-b1b6-0b60437ba96e)
Looking int the customLigthts.prefs it says:
```
customPreset0=DF:88:56:D0:72:A8|8|80|44;CE:D9:49:A3:1F:F7|8|40|44;C0:50:A7:8C:95:BA|5|0|44;CB:72:58:58:26:64|8|4|44;DB:64:76:35:00:A5|5|0|44
customPreset1=CE:D9:49:A3:1F:F7|5|50|44;C0:50:A7:8C:95:BA|5|60|44;DF:88:56:D0:72:A8|5|100|44;CB:72:58:58:26:64|5|5|44;DB:64:76:35:00:A5|5|60|44
customPreset2=C0:50:A7:8C:95:BA|5|74|44;DF:88:56:D0:72:A8|5|48|44;CE:D9:49:A3:1F:F7|5|49|44;CB:72:58:58:26:64|5|4|44;DB:64:76:35:00:A5|5|74|44
```

So can I resolve this somehow?

**Comment by taburineagle** [comment]
Hehe, Zach actually, but that's fine 😊  Ah, yeah, that one is on me - I'm planning on releasing a new version very soon that adds support for the Infinity series of Neewer lights, and I had to make some changes to the way presets are stored to get them to "behave better" when using a combination of both old-style and Infinity-style Neewer lights, as the Infinity protocol is different than the old-style ones.  I pushed the latest changes to the main branch over the weekend, but hadn't had a chance to make the update official yet, so I haven't had a chance to mention that yet 😑  Although as I take a look at it, there are a few other things I need to iron out first, as I tried to recreate those settings you had verbatim, but my current version can't take OFF as a parameter to store, just yet (that _also_ works different between the light sets)... so I have more work to do first.

I'd suggest going back to the last released version (or the last version you had before), if it's possible to, for now.  Although if you'd like to keep trying the new version, use this version of customLights.prefs - it's not 100% what the old snapshot presets were (I have the lights in the first preset all dimming to 0% at the moment, as I'm working on the ON/OFF logic with both sets of lights), but it should replicate the settings you had before:

```
customPreset0=DF:88:56:D0:72:A8|120|135|2|0|56|50;CE:D9:49:A3:1F:F7|120|135|2|0|56|50;C0:50:A7:8C:95:BA|120|135|2|0|44|50;CB:72:58:58:26:64|120|135|2|0|56|50;DB:64:76:35:00:A5|120|135|2|0|44|50
customPreset1=CE:D9:49:A3:1F:F7|120|135|2|50|44|50;C0:50:A7:8C:95:BA|120|135|2|60|44|50;DF:88:56:D0:72:A8|120|135|2|100|44|50;CB:72:58:58:26:64|120|135|2|5|44|50;DB:64:76:35:00:A5|120|135|2|60|44|50
customPreset2=C0:50:A7:8C:95:BA|120|135|2|74|44|50;DF:88:56:D0:72:A8|120|135|2|48|44|50;CE:D9:49:A3:1F:F7|120|135|2|49|44|50;CB:72:58:58:26:64|120|135|2|4|44|50;DB:64:76:35:00:A5|120|135|2|74|44|50
```

**Comment by taburineagle** [comment]
Hi Kenneth @fribse  - I'm working on writing a converter on the loadPresets() function that will take an old presets file and convert it to a new one.  It's not ready yet (I still need to work a bit more on the "off" function), but all of the parameters are converting properly.

**Comment by taburineagle** [comment]
OK, @fribse - I have re-merged the work branch back into the main branch.  The latest version on the main branch should work fine with the old presets file, I tested it using the parameters you originally gave, and all showed fine in the HTTP server's main page:

![image](https://github.com/taburineagle/NeewerLite-Python/assets/18430526/cf37c46c-95f5-4675-aa38-9031dd4e48c5)

I'm going to close this one as completed for now, let me know if you have any issues with it!
